# Generated by Django 3.1.2 on 2020-10-25 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trucks',
            old_name='semitariler',
            new_name='semitrailer',
        ),
    ]
