# Generated by Django 3.1.2 on 2020-10-25 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0002_auto_20201025_1152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trucks',
            new_name='Truck',
        ),
    ]
