# Generated by Django 3.1.2 on 2020-10-25 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0003_auto_20201025_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truck',
            old_name='car',
            new_name='car_manufacturer',
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trucks.truck')),
            ],
        ),
    ]
